### ISSUE TITLE
Issue building on Ubuntu

### ISSUE THREAD

**Issue by jjcm** [nvs/lua-stormlib#12]
Having an issue building gem td on Ubuntu currently. Error is as so: 

```
j@DESKTOP-D6S7COI:/mnt/c/Users/j/code/gem$ lua map/build etc/gem.lua
Building...
lua: error loading module 'stormlib' from file '/usr/local/lib/lua/5.3/stormlib.so':
        /usr/local/lib/lua/5.3/stormlib.so: undefined symbol: __gxx_personality_v0
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        ./map/file/w3x.lua:7: in main chunk
        [C]: in function 'require'
        ./map/task/build/w3x/read.lua:4: in main chunk
        [C]: in function 'require'
        ./map/tasks.lua:73: in function 'map.tasks.run'
        (...tail calls...)
        [C]: in ?
        
```

For reference, here's the cmake command I'm using to build StormLib:
`cmake -DCMAKE_CXX_FLAGS=-"fPIC -lstdc++" -DCMAKE_C_FLAGS="-fPIC -lstdc++" -DCMAKE_BUILD_TYPE=debug -DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF -G "Unix Makefiles" CMakeLists.txt`

Any idea what's going on here?

**Comment by nvs** [comment]
I've been using `-DBUILD_SHARED_LIBS=on`. Luarocks does not work with static libraries, as such shared are required.

Also, you have a typo (that does not seem to matter) here:

```diff
-DCMAKE_CXX_FLAGS=-"fPIC -lstdc++"
```

**Comment by nvs** [comment]
Are you building StormLib as a shared or static library? I use `-DBUILD_SHARED_LIBS=on`. Luarocks does not presently support static libraries. Omitting this flag prevents me from building lua-stormlib (when not specifying the generator with `-G`). I'll probably add a note about this to the README.

Also, you have a typo (that does not seem to matter) here:

```diff
-cmake -DCMAKE_CXX_FLAGS=-"fPIC -lstdc++"
+cmake -DCMAKE_CXX_FLAGS="-fPIC -lstdc++"
```

**Comment by nvs** [comment]
I should update that I was able to produce the exact error as encountered by @jjcm. First, I built StormLib while using the following minimal command: : `cmake -G "Unix Makefiles" CMakeLists.txt`. Specifying the generator (i.e. `-G`) allowed me to then build lua-stormlib (which failed without it due to Luarocks only supporting shared libraries). Use of lua-stormlib produced the same error.

The issue was resolved by using: `cmake -DBUILD_SHARED_LIBS=on -G "Unix Makefiles" CMakeLists.txt`. Indicating the desire for a shared library also allowed building lua-stormlib when not specifying a generator. 

I'm going to close this as I believe this will resolve the problem. If it doesn't, please reopen the issue.
